version: '3.1'

services:

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    # volumes:
    #   - ${VOLUMES}/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: photos
