@host=http://localhost:8080

GET {{host}}/api/users/John%20Doe3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG4gRG9lMiJ9.EM1z9O4iOP6PIA9TrrSW6uS6FssvnLwrn9WAt8nCMLc

POST {{host}}/user
Content-Type: application/json

{
    "username":"John Doe3",
    "password":"my weak password",
    "email":"example3@example.com",
    "phone":"+573105236382"
}

POST {{host}}/login
Content-Type: application/json

{
    "email":"example2@example.com",
    "password":"my weak password"
}


POST {{host}}/api/photos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG4gRG9lMiJ9.EM1z9O4iOP6PIA9TrrSW6uS6FssvnLwrn9WAt8nCMLc

-F "uploads=@./black_rot2.jpg"

GET {{host}}/api/photos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG4gRG9lMiJ9.EM1z9O4iOP6PIA9TrrSW6uS6FssvnLwrn9WAt8nCMLc

DELETE {{host}}/api/photos/eeaf9f3d-f4fc-4f54-8d4c-f325cbbe3730.jpg
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG4gRG9lMiJ9.EM1z9O4iOP6PIA9TrrSW6uS6FssvnLwrn9WAt8nCMLc

GET {{host}}/api/photos/71a95f59-4a67-4ef0-91ef-4d2d3113bc8f.jpg
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG4gRG9lMiJ9.EM1z9O4iOP6PIA9TrrSW6uS6FssvnLwrn9WAt8nCMLc

GET {{host}}/api/results/71a95f59-4a67-4ef0-91ef-4d2d3113bc8f.jpg
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG4gRG9lMiJ9.EM1z9O4iOP6PIA9TrrSW6uS6FssvnLwrn9WAt8nCMLc

GET {{host}}/api/results
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG4gRG9lMiJ9.EM1z9O4iOP6PIA9TrrSW6uS6FssvnLwrn9WAt8nCMLc
